"""
dhtrader: Trading analysis module

Public API exports domain classes and storage functions.
"""
from .dhtypes import (
    Backtest,
    Candle,
    Chart,
    Day,
    Event,
    Indicator,
    IndicatorDataPoint,
    IndicatorEMA,
    IndicatorSMA,
    Symbol,
    Trade,
    TradeSeries,
)

from .dhcommon import (
    bot,
    check_tf_th_compatibility,
    diff_dicts,
    dow_name,
    dt_as_dt,
    dt_as_str,
    dt_as_time,
    dt_from_epoch,
    dt_to_epoch,
    expected_candle_datetimes,
    log_say,
    next_candle_start,
    OperationTimer,
    ProgBar,
    prompt_yn,
    sort_dict,
    summarize_candles,
    this_candle_start,
    timeframe_delta,
    valid_timeframe,
    valid_trading_hours,
)

from .dhutil import (
    compare_candles_vs_csv,
    generate_zero_volume_candle,
    read_candles_from_csv,
    remediate_candle_gaps,
    store_candles_from_csv,
)

try:
    from .dhstore import (
        clear_events,
        delete_backtests,
        delete_backtests_by_field,
        delete_candles,
        delete_indicator,
        delete_trades,
        delete_trades_by_field,
        delete_tradeseries,
        delete_tradeseries_by_field,
        get_all_backtests,
        get_all_tradeseries,
        get_backtests_by_field,
        get_candles,
        get_events,
        get_indicator,
        get_indicator_datapoints,
        get_symbol_by_ticker,
        get_trades_by_field,
        get_tradeseries_by_field,
        list_indicators_names,
        review_backtests,
        review_candles,
        review_indicators,
        review_trades,
        review_tradeseries,
        store_backtests,
        store_candle,
        store_candles,
        store_event,
        store_indicator,
        store_trades,
        store_tradeseries,
    )
except Exception:
    # dhstore requires MongoDB configuration, skip if not available
    pass

__all__ = [
    'Backtest',
    'bot',
    'Candle',
    'Chart',
    'check_tf_th_compatibility',
    'clear_events',
    'compare_candles_vs_csv',
    'Day',
    'delete_backtests',
    'delete_backtests_by_field',
    'delete_candles',
    'delete_indicator',
    'delete_trades',
    'delete_trades_by_field',
    'delete_tradeseries',
    'delete_tradeseries_by_field',
    'diff_dicts',
    'dow_name',
    'dt_as_dt',
    'dt_as_str',
    'dt_as_time',
    'dt_from_epoch',
    'dt_to_epoch',
    'Event',
    'expected_candle_datetimes',
    'generate_zero_volume_candle',
    'get_all_backtests',
    'get_backtests_by_field',
    'get_all_tradeseries',
    'get_candles',
    'get_events',
    'get_indicator',
    'get_indicator_datapoints',
    'get_symbol_by_ticker',
    'get_trades_by_field',
    'get_tradeseries_by_field',
    'Indicator',
    'IndicatorDataPoint',
    'IndicatorEMA',
    'IndicatorSMA',
    'list_indicators_names',
    'log_say',
    'next_candle_start',
    'OperationTimer',
    'ProgBar',
    'prompt_yn',
    'read_candles_from_csv',
    'remediate_candle_gaps',
    'review_backtests',
    'review_candles',
    'review_indicators',
    'review_trades',
    'review_tradeseries',
    'sort_dict',
    'store_backtests',
    'store_candle',
    'store_candles',
    'store_candles_from_csv',
    'store_event',
    'store_indicator',
    'store_trades',
    'store_tradeseries',
    'summarize_candles',
    'Symbol',
    'this_candle_start',
    'timeframe_delta',
    'Trade',
    'TradeSeries',
    'valid_timeframe',
    'valid_trading_hours',
]

__version__ = '1.0.0'
